import { SlashCommandBuilder, } from 'discord.js';
const FOUNDER_ROLE_ID = '1470554645364478016';
export const data = new SlashCommandBuilder()
    .setName('guildrestore')
    .setDescription('Restores guild system data from a JSON backup file')
    .addAttachmentOption(option => option
    .setName('file')
    .setDescription('Backup JSON file generated by /guildbackup')
    .setRequired(true))
    .addStringOption(option => option
    .setName('mode')
    .setDescription('Restore mode')
    .setRequired(false)
    .addChoices({ name: 'merge (keep existing + add/update)', value: 'merge' }, { name: 'replace (erase current data first)', value: 'replace' }));
function ensureArray(value) {
    return Array.isArray(value) ? value : [];
}
export async function execute(interaction, db) {
    try {
        if (!interaction.guildId || !interaction.guild) {
            await interaction.editReply({
                content: 'This command can only be used in a server.',
            });
            return;
        }
        const actorMember = await interaction.guild.members.fetch(interaction.user.id).catch(() => null);
        const canRestore = !!actorMember && actorMember.roles.cache.has(FOUNDER_ROLE_ID);
        if (!canRestore) {
            await interaction.editReply({
                content: '❌ Only Founder can use this command.',
            });
            return;
        }
        const file = interaction.options.getAttachment('file', true);
        const mode = interaction.options.getString('mode') || 'merge';
        if (!file.name?.toLowerCase().endsWith('.json')) {
            await interaction.editReply({
                content: '❌ Invalid file type. Please provide a `.json` backup file.',
            });
            return;
        }
        const response = await fetch(file.url);
        if (!response.ok) {
            await interaction.editReply({
                content: '❌ Failed to download backup file from Discord.',
            });
            return;
        }
        const text = new TextDecoder().decode(await response.arrayBuffer());
        let payload;
        try {
            payload = JSON.parse(text);
        }
        catch {
            await interaction.editReply({
                content: '❌ Invalid JSON backup file.',
            });
            return;
        }
        if (!payload || typeof payload !== 'object' || !payload.tables) {
            await interaction.editReply({
                content: '❌ Invalid backup structure.',
            });
            return;
        }
        const guilds = ensureArray(payload.tables.Guilds);
        const managers = ensureArray(payload.tables.Managers);
        const mains = ensureArray(payload.tables.MainRosters);
        const subs = ensureArray(payload.tables.SubRosters);
        const invites = ensureArray(payload.tables.Invites);
        const wars = ensureArray(payload.tables.Wars);
        const wagers = ensureArray(payload.tables.Wagers);
        const runRestore = db.transaction(() => {
            if (mode === 'replace') {
                db.prepare('DELETE FROM Wagers').run();
                db.prepare('DELETE FROM Wars').run();
                db.prepare('DELETE FROM Invites').run();
                db.prepare('DELETE FROM Managers').run();
                db.prepare('DELETE FROM MainRosters').run();
                db.prepare('DELETE FROM SubRosters').run();
                db.prepare('DELETE FROM Guilds').run();
            }
            const insertGuild = db.prepare(`INSERT OR REPLACE INTO Guilds (id, name, leaderId, coLeaderId, imageUrl, panelMessageId, panelChannelId, wins, losses, region, createdAt)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);
            const insertManager = db.prepare(`INSERT OR IGNORE INTO Managers (guildId, userId, createdAt)
         VALUES (?, ?, ?)`);
            const insertMain = db.prepare(`INSERT OR IGNORE INTO MainRosters (guildId, userId, createdAt)
         VALUES (?, ?, ?)`);
            const insertSub = db.prepare(`INSERT OR IGNORE INTO SubRosters (guildId, userId, createdAt)
         VALUES (?, ?, ?)`);
            const insertInvite = db.prepare(`INSERT OR REPLACE INTO Invites (id, guildId, targetUserId, roleType, inviterId, status, createdAt, expiresAt)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)`);
            const insertWar = db.prepare(`INSERT OR REPLACE INTO Wars (id, openerGuildId, opponentGuildId, channelId, status, createdByUserId, acceptedByUserId, acceptedByGuildId, resultGuildId, winnerScore, loserScore, clipsLink, panelMessageId, createdAt, closedAt)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);
            const insertWager = db.prepare(`INSERT OR REPLACE INTO Wagers (id, type, channelId, challenger1Id, challenger2Id, challenged1Id, challenged2Id, status, acceptedByUserIds, dodgedByUserId, panelMessageId, createdAt, closedAt)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);
            for (const row of guilds) {
                insertGuild.run(row.id, row.name, row.leaderId, row.coLeaderId ?? null, row.imageUrl ?? null, row.panelMessageId ?? null, row.panelChannelId ?? null, Number(row.wins || 0), Number(row.losses || 0), row.region, row.createdAt ?? new Date().toISOString());
            }
            for (const row of managers) {
                insertManager.run(row.guildId, row.userId, row.createdAt ?? new Date().toISOString());
            }
            for (const row of mains) {
                insertMain.run(row.guildId, row.userId, row.createdAt ?? new Date().toISOString());
            }
            for (const row of subs) {
                insertSub.run(row.guildId, row.userId, row.createdAt ?? new Date().toISOString());
            }
            for (const row of invites) {
                insertInvite.run(row.id, row.guildId, row.targetUserId, row.roleType, row.inviterId ?? null, row.status, row.createdAt ?? new Date().toISOString(), row.expiresAt ?? null);
            }
            for (const row of wars) {
                insertWar.run(row.id, row.openerGuildId, row.opponentGuildId, row.channelId, row.status, row.createdByUserId, row.acceptedByUserId ?? null, row.acceptedByGuildId ?? null, row.resultGuildId ?? null, row.winnerScore ?? null, row.loserScore ?? null, row.clipsLink ?? null, row.panelMessageId ?? null, row.createdAt ?? new Date().toISOString(), row.closedAt ?? null);
            }
            for (const row of wagers) {
                insertWager.run(row.id, row.type, row.channelId, row.challenger1Id, row.challenger2Id ?? null, row.challenged1Id, row.challenged2Id ?? null, row.status, row.acceptedByUserIds ?? '[]', row.dodgedByUserId ?? null, row.panelMessageId ?? null, row.createdAt ?? new Date().toISOString(), row.closedAt ?? null);
            }
        });
        runRestore();
        await interaction.editReply({
            content: `✅ Restore completed in **${mode}** mode.\n` +
                `Guilds: **${guilds.length}** | Managers: **${managers.length}** | Main: **${mains.length}** | Sub: **${subs.length}** | Invites: **${invites.length}** | Wars: **${wars.length}** | Wagers: **${wagers.length}**`,
        });
    }
    catch (error) {
        console.error('Error executing /guildrestore:', error);
        await interaction.editReply({
            content: '❌ An unexpected error occurred while restoring backup.',
        });
    }
}
//# sourceMappingURL=guildrestore.js.map